version: '3.1'
services:

  # nginx container #########################################
  nginx:
    image: nginx:stable-alpine
    container_name: ser_nginx
    volumes:
      - /home/max/workspace/app/nginx/conf.d:/etc/nginx/conf.d
      - /home/max/workspace/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/max/workspace/app/www:/home/www
    ports:
      - "80:80"
      - "100:100"
      - "101:101"
      - "110:110"
    environment:
      - NGINX_PORT=80
    restart: always
  ### portainer docker manager web ############################
  portainer:
    image: portainer/portainer-ce
    restart: always
    environment:
      - VIRTUAL_HOST=dev.portainer
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
  ### mongo container #########################################
  mongo:
    image: mongo
    restart: always
    container_name: ser_mongo
    volumes:
      - /home/max/workspace/services/mongodb:/workspace/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  ### node_dev container #########################################
  node_dev:
    image: node:lts
    container_name: node_dev
    volumes:
      - /home/max/workspace/dev:/workspace
    ports:
      - "13010:13010"
    tty: true
    restart: always
  ### alist container #########################################
  alist:
    restart: always
    volumes:
        - '/etc/alist:/opt/alist/data'
    ports:
        - '5244:5244'
    environment:
        - PUID=0
        - PGID=0
        - UMASK=022
    container_name: alist
    image: 'xhofe/alist:latest'
  ### jellyfin container #########################################        
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.2.100 #optional
    volumes:
      - /home/max/homelab/workspace/app/jellyfin/library:/config
      - /home/max/homelab/files/video/tvshows:/data/tvshows
      - /home/max/homelab/files/video/movies:/data/movies
      - /home/max/homelab/files/video/cartoon:/data/cartoon
      - /home/max/homelab/files/video/lighthouse:/data/lighthouse       
    ports:
      - 12000:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
volumes:
  portainer_data:
